# Generated by Django 5.2.6 on 2025-09-26 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_mount',
            new_name='total_amount',
        ),
    ]
