# Generated by Django 5.2.6 on 2025-09-26 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_rename_total_mount_order_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='Service_title',
            new_name='service_title',
        ),
    ]
